# =========================
# HTTP LISTENERS
# =========================
http.host=0.0.0.0
http.port.soap.empleados=9091
http.port.rest.niveles=9092
http.port.proceso.nenv=9093
http.port.proceso.nunvts=9094

# =========================
# DATABASE
# =========================
db.host=127.0.0.1
db.port=3307
db.name=mtis
db.user=root
db.password=Jess89

# =========================
# SMTP / fakeSMTP
# =========================
smtp.host=127.0.0.1
smtp.port=25
smtp.from=noreply@mtis.local

# =========================
# PRACTICA 1 SOAP
# =========================
soap.empleados.address=http://127.0.0.1:8080/axis2/services/EmpleadosSOAP
soap.controlpresencia.address=http://127.0.0.1:8080/axis2/services/ControlPresenciaSOAP

# =========================
# PRACTICA 1 REST
# =========================
rest.p1.protocol=HTTP
rest.p1.host=127.0.0.1
rest.p1.port=8081
rest.p1.basepath=/api/v1

# =========================
# ACTIVEMQ (JMS)
# OJO: aquí va el puerto JMS/OpenWire, no el STOMP
# =========================
jms.broker.url=tcp://127.0.0.1:61616
jms.user=admin
jms.password=Jess89

# =========================
# SALIDAS APARTADO 1
# =========================
files.empleados.outputDir=./salidas/empleados

# =========================
# EMAIL ERRORES
# =========================
smtp.to.errors=admin@mtis.local